version: '2.0'

services:
  app-myobe:
    build:
      context: ./docker-src
      dockerfile: nginx.dockerfile
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    volumes:
      - '.:/usr/share/nginx/html'
      - './docker-src/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8080:80'
  fpm-myobe:
    build:
      context: ./docker-src
      dockerfile: fpm.dockerfile
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    volumes:
      - '.:/usr/share/nginx/html'
  composer:
    build:
      context: ./docker-src
      dockerfile: composer.dockerfile
    volumes:
      - '.:/usr/share/nginx/html'
    working_dir: '/usr/share/nginx/html'
    entrypoint: ["composer"]
  artisan:
    build:
      context: ./docker-src
      dockerfile: artisan.dockerfile
    volumes:
    - '.:/usr/share/nginx/html'
    working_dir: '/usr/share/nginx/html'
    entrypoint: ["php", "/usr/share/nginx/html/artisan"]
  mariadb-myobe:
    image: mariadb
    environment:
      - 'MARIADB_ROOT_PASSWORD:pass'
    volumes:
      - './docker-src/myobe_db:/var/lib/mysql'
  npm:
    image: node:16.17.0-slim
    volumes:
    - '.:/usr/share/nginx/html'
    working_dir: '/usr/share/nginx/html'
    entrypoint: ["npm"]
